apiVersion: v1
kind: Service
metadata:
  name: node-msk-notifier-api
  namespace: notifications
  labels:
    app.kubernetes.io/name: node-msk-notifier-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: node-msk-notifier-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
